workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - build 
  - deploy

deploy-server:
  tags:
    - heavy
    - linux_amd64
  stage: deploy 
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  image: quay.io/buildah/stable
  variables:
    # Use vfs with buildah. Docker offers overlayfs as a default, but Buildah
    # cannot stack overlayfs on top of another overlayfs filesystem.
    STORAGE_DRIVER: vfs
    # Write all image metadata in the docker format, not the standard OCI format.
    # Newer versions of docker can handle the OCI format, but older versions, like
    # the one shipped with Fedora 30, cannot handle the format.
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
    FQ_IMAGE_NAME: "databending/${CONTAINER_NAME}:latest"
  before_script:
    - buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" docker.io 
  script:
    - buildah images 
    - buildah build --platform=linux/amd64 -t $FQ_IMAGE_NAME 
    - buildah images 
    - |-
      if [ "$CI_COMMIT_BRANCH" = "master" ]; then
          buildah push $FQ_IMAGE_NAME
      fi

server:
  stage: build 
  image:
    name: rust:slim-bookworm
    entrypoint: [""]
  script:
    - apt-get update -y
    - apt-get -y install pkg-config libssl-dev git make protobuf-compiler
    - git config --global credential.helper store
    - |-
      if [ -n "$CI_JOB_TOKEN" ]; then \
        echo "https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.databending.ca" > ~/.git-credentials; \
      else \
        echo "https://oauth2:$GIT_TOKEN@gitlab.databending.ca" > ~/.git-credentials; \
      fi
    - rustup default nightly
    - RUSTFLAGS="--cfg tokio_unstable"  cargo +nightly build --bin server --release 
    - cargo install --locked tokio-console --root ./ 
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - target/release/*
  artifacts:
    paths:
      - target/release/server
      - bin/tokio-console 
    expire_in: 1 day


