build_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.19.2-debug
    entrypoint: [""]
  script:
    - |-
      if [ "$CI_COMMIT_BRANCH" = "master" ]; then
        /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --build-arg CI_JOB_TOKEN="${CI_JOB_TOKEN}" --build-arg GIT_TOKEN="${GIT_TOKEN}" --destination "databending/${CONTAINER_NAME}:${CI_COMMIT_TAG}"
      else  
        /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --build-arg CI_JOB_TOKEN="${CI_JOB_TOKEN}" --build-arg GIT_TOKEN="${GIT_TOKEN}" --destination "databending/${CONTAINER_NAME}:dev"
      fi
