[package]
name = "immortal-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
serde = {version = "1.0.219", features=["derive"]}
tonic = "0.14.2"
# immortal-macros = { path = "../immortal-macros" }
simd-json = {version="0.15.1"}
prost-wkt = "0.7"
prost-wkt-types = "0.7"
prost-types = "0.14.1"
prost = "0.14.1"
tonic-prost = "0.14.1"

[build-dependencies]
tonic-build = "0.14.1"
prost-wkt-build = "0.7"
tonic-prost-build = "0.14.1"
