[lib]
proc-macro = true

[package]

name = "immortal-macros"
version = "0.1.0"
edition = "2021"


[dependencies]
schemars = "0.8.21"
syn = { version = "2.0.85", features = ["full"] }
quote = "1.0.37"
proc-macro2 = "1.0.89"
serde_json = "1.0.132"
